name: Dev -> Main

on:
  schedule:
    - cron:  '21 3 * * 3,6'
  workflow_dispatch:

jobs:
  develop-to-main:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Merge develop to main    
      uses: everlytic/branch-merge@1.1.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_ref: 'develop'
        target_branch: 'main'
        commit_message_template: '[Automated] Merged {source_ref} into {target_branch}'
